# Use a imagem oficial do PostgreSQL
FROM postgres:latest

# Defina as variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=literalura

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432

# docker build -t my-postgres .

# docker run -d -p 5432:5432 --name my-postgres-container my-postgres
